import pickle
from analyse_posts_data import analyze

swipwe_ups = pickle.load(open("storys.json", "rb"))
posts = pickle.load(open("posts.json", "rb"))
errors = pickle.load(open("error_log.txt", "rb"))

print("SWIPE UP LINKS")
print("-"*70)
print("\n".join(list(swipwe_ups)))
print("-"*70)
print("SWIPE UP LINKS")
print()
print()
input("Next is Error Log, press a key to go on...")
print()
print("ERROR LOG")
print("-"*70)
print("".join(errors))
print("-"*70)
print("ERROR LOG")
print()
print()
input("Next is Data from Posts, press a key to go on...")
print()
print("DATA from POSTS (sentences with keywords)")
print("-"*70)
analyze()
print("-"*70)
print("DATA from POSTS (sentences with keywords)")
